Mscr 116
CSCfi/mscr-datamodel-api pull request #11
Opened 2023-06-08 12:26 UTC by username-u

2023-06-09 06:49 UTC, jkesanie requested changes

2023-06-09 06:49 UTC, jkesanie commented on src/main/java/fi/vm/yti/datamodel/api/v2/endpoint/Schema.java
> +				if (validationStatus) {
Rename validatationStatus variable. It is difficult to understand whether the if block should be executed or not just by reading the line "if(validatationStatus)".  Compared to for example "if(isValidJSON)"

2023-06-09 06:49 UTC, jkesanie commented on src/main/resources/schema_v4 copy
Do we need this file?

2023-06-09 06:49 UTC, jkesanie commented on src/test/java/fi/vm/yti/datamodel/api/v2/service/JSONValidationServiceTest.java
> +		assertEquals(JSONValidationService.validateJSON(byteStreamFromPath(validInputSchemaPath)), new ValidationRecord(true, Arrays.asList()));
validataJSON() method does not exist. Have you compiled the code? Does the tests run successfully?

2023-06-09 06:49 UTC, jkesanie commented on src/test/java/fi/vm/yti/datamodel/api/v2/service/SchemaServiceTest.java
> +
Clean up

2023-06-09 07:05 UTC, username-u commented on src/main/resources/schema_v4 copy
not anymore

2023-06-13 09:18 UTC, jkesanie approved these changes

2023-06-13 10:06 UTC, merged