Mscr 119
CSCfi/mscr-datamodel-api pull request #7
Opened 2023-06-05 08:44 UTC by username-u

2023-06-07 07:24 UTC, jkesanie commented on build.gradle
Cleanup

2023-06-07 07:27 UTC, jkesanie requested changes

2023-06-07 07:27 UTC, jkesanie commented on src/main/java/fi/vm/yti/datamodel/api/v2/dto/ModelConstants.java
Cleanup

2023-06-07 07:27 UTC, jkesanie commented on src/main/java/fi/vm/yti/datamodel/api/v2/dto/SchemaDTO.java
> +
Insert nitpicking here

2023-06-07 07:27 UTC, jkesanie commented on src/main/java/fi/vm/yti/datamodel/api/v2/mapper/OrganizationMapper.java
Cleanup

2023-06-07 07:27 UTC, jkesanie commented on src/main/java/fi/vm/yti/datamodel/api/v2/service/impl/PostgresStorageService.java
Clean up

2023-06-07 07:27 UTC, jkesanie commented on src/main/resources/logback-spring.xml
Revert these changes. The Default logging level should be INFO.

2023-06-08 06:19 UTC, username-u commented on src/main/java/fi/vm/yti/datamodel/api/v2/dto/ModelConstants.java
> -    public static final List<String> USED_LANGUAGES = List.of("fi", "sv", "en");
no whitespace

2023-06-09 05:46 UTC, jkesanie approved these changes
I added a commit to revert the logging configs back to less verbose ones. 
Otherwise ok.

2023-06-09 06:11 UTC, merged